session_name: tmux-config-update
windows:
- layout: ace2,85x22,0,0,5
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command: bash
  start_directory: /home/ma/sit-project
  window_name: org-file
- focus: 'true'
  layout: ace3,85x22,0,0,6
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command: python3
  start_directory: /home/ma/sit-project
  window_name: tangled
- layout: ace4,85x22,0,0,7
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command: bash
  start_directory: /home/ma/sit-project
  window_name: command line
